//Assignment 1-- short answer;

// what is Backend: Backend is the server-side part of an application that processes data and manages databases.

//what is Java: Java is a high-level, object-oriented programming language used to build platform-independent applications.

//why java is Platform Independent: Java is platform independent because it uses bytecode executed by the JVM.

//DB--JDK, JRE, JVM: JDK is for development, JRE is for running programs, and JVM executes bytecode.

//what is JVM: JVM is a virtual machine that runs Java bytecode on any platform.

//what is Bytecode: Bytecode is the intermediate code generated by the Java compiler.

//what is a Variable: A variable is a named memory location used to store data.

//why do we need Data Types: Data types define the type and size of data a variable can hold.

//what is Strongly Typed Language: A strongly typed language strictly enforces data type rules.

//what is Type Casting: Type casting is the conversion of one data type into another.
