//Assignment 1-- short answer;

//  Backend: Backend is the server-side part of an application that processes data and manages databases.

// Java: Java is a high-level, object-oriented programming language used to build platform-independent applications.

//why java is Platform Independent: Java is platform independent because it uses bytecode executed by the JVM.

//DB--JDK, JRE, JVM: JDK is for development, JRE is for running programs, and JVM executes bytecode.

// JVM: JVM is a virtual machine that runs Java bytecode on any platform.

// Bytecode: Bytecode is the intermediate code generated by the Java compiler.

// Variable: A variable is a named memory location used to store data.

//why do we need Data Types: Data types define the type and size of data a variable can hold.

//what is Strongly Typed Language: A strongly typed language strictly enforces data type rules.

//what is Type Casting: Type casting is the conversion of one data type into another.

//Assignment 2;
// 1. explain java execution flow
// source code written-compilation-class loading-bytecode verification-execution
// example;
 class main{
  public static void main(String[] args) {
      System.out.println("Hello,World!");
  }
}

//2.explain implicit type casting
// java automatically converts a smaller data type into larger data
// byte-short-int-long-float-double
// example;
class ImplicitCasting {
    public static void main(String[] args) {
        int a = 25;      
        double b = a; 

        System.out.println("Integer value: " + a);
        System.out.println("Double value: " + b);
    }
}
//3 explain explicit type casting
//converts a larger data type into a smaller data type by specifying the target type.
//double → float → long → int → short → byte
// example;
class ExplicitCasting {
    public static void main(String[] args) {
        double a = 45.89;      
        int b = (int) a;      

        System.out.println("Double value: " + a);
        System.out.println("Integer value: " + b);
    }
}

//4 diff between primitive and non primitive data type
// primitive --basic building block of programming like(int,char,boolean)
// non primitive--more complex,user defined like(arrays,classes,interfaces)

//5 diff between if-else and switch-case
// if-else--Used for decision-making with multiple conditions (logical, relational, ranges).
public class IfElseExample {
    public static void main(String[] args) {
        int day = 3;

        if (day == 1) {
            System.out.println("Monday");
        } else if (day == 2) {
            System.out.println("Tuesday");
        } else if (day == 3) {
            System.out.println("Wednesday");
        } else {
            System.out.println("Other day");
        }
    }
}
// switch-case-Used when a single variable/expression is compared against multiple constant values.
public class SwitchExample {
    public static void main(String[] args) {
        int day = 3;

        switch (day) {
            case 1:
                System.out.println("Monday");
                break;
            case 2:
                System.out.println("Tuesday");
                break;
            case 3:
                System.out.println("Wednesday");
                break;
            default:
                System.out.println("Other day");
        }
    }
}






